-- begin CARSALE_CAR
alter table CARSALE_CAR add constraint FK_CARSALE_CAR_CAR_MODEL_ID foreign key (CAR_MODEL_ID) references CARSALE_CAR_MODEL(ID)^
alter table CARSALE_CAR add constraint FK_CARSALE_CAR_CARD_ID foreign key (CARD_ID) references WF_CARD(ID)^
create index IDX_CARSALE_CAR_CAR_MODEL on CARSALE_CAR (CAR_MODEL_ID)^
-- end CARSALE_CAR
-- begin CARSALE_CAR_PURCHASE
alter table CARSALE_CAR_PURCHASE add constraint FK_CARSALE_CAR_PURCHASE_CAR_ID foreign key (CAR_ID) references CARSALE_CAR(CARD_ID)^
alter table CARSALE_CAR_PURCHASE add constraint FK_CARSALE_CAR_PURCHASE_CUSTOMER_ID foreign key (CUSTOMER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table CARSALE_CAR_PURCHASE add constraint FK_CARSALE_CAR_PURCHASE_BANK_ID foreign key (BANK_ID) references DF_BANK(ID)^
alter table CARSALE_CAR_PURCHASE add constraint FK_CARSALE_CAR_PURCHASE_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_CARSALE_CAR_PURCHASE_CUSTOMER on CARSALE_CAR_PURCHASE (CUSTOMER_ID)^
create index IDX_CARSALE_CAR_PURCHASE_CAR on CARSALE_CAR_PURCHASE (CAR_ID)^
create index IDX_CARSALE_CAR_PURCHASE_BANK on CARSALE_CAR_PURCHASE (BANK_ID)^
-- end CARSALE_CAR_PURCHASE
